### PR TITLE
Update Lodash to latest version

### PR DESCRIPTION
**Pull request by XVincentX**
This PR will update Lodash to latest version helping me and other utilisers to deduplicate the dependency where needed.

### CODE REVIEW

**Comment by smizell** [comment]
@XVincentX Give me a day or so to sort this out. Since I didn't add CI testing (gasp) and since I haven't set up Node/NPM on my computer (double gasp), I will have to do that to make sure things are passing and then be able to publish.

If you need this faster and would be interested in doing any of this yourself, I'd be happy to add you as contributor.

**Comment by smizell** [comment]
@XVincentX I now have this repo using Travis. Can you rebase or push a commit to force a build? Not sure what will be needed to make that happen.

**Comment by XVincentX** [comment]
@smizell I was out for vacation - I just did it.

**Comment by smizell** [comment]
@XVincentX Published to NPM as 0.4.1. Is this update for Minim>

**Comment by XVincentX** [comment]
@smizell Well now the fun part begins. 
I should now try to track the release train to make sure `fury-adapter-swagger` has latest lodash. Unfortunately I do not remember how I came up here.

Would you mind upgrading minim, eventually?

**Comment by smizell** [comment]
@XVincentX Not at all. I think these libraries should be bumped to 1.0.0 and use semantic release plus Greenkeeper.

I believe several others have access to Minim as collaborators. If you want to join in on that, let me know too.

**Comment by XVincentX** [comment]
I might join, but honestly I do not know how much I'd be able to contribute in. I'm just an user here.

**Comment by smizell** [comment]
No obligation. Just offering in case it would make these kinds of things easier. Happy to just do PRs like this.

**Pull request merged**
